#Database
POSTGRESQL_USERNAME: user
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: 192.168.1.34
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: securedocmanagementdb

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Email Config:
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: google@gmail.com
EMAIL_PASSWORD: google
VERIFY_EMAIL_HOST: http://localhost:8085